"""
HRDocForensics — Score conversion, band selection, and recommendation text.

All logic here is DETERMINISTIC (code, not LLM):
- authenticity_score = round((100 - fakeness_score) / 10, 1)
- Band and recommendation text come from config/recommendations.json.
- Verification steps are hard-coded, never generated by the LLM.
"""

from __future__ import annotations

from typing import Any

from app.core.config import load_recommendations_json


def compute_authenticity_score(fakeness_score: int) -> float:
    """Convert LLM fakeness_score (0-100) to authenticity_score (0-10).

    Higher = more genuine.
    """
    return round((100 - fakeness_score) / 10, 1)


def select_band(authenticity_score: float) -> dict[str, Any]:
    """Select the appropriate band from config/recommendations.json.

    Returns the band dict with key, label, colour, recommendation text,
    and show_cross_check flag.
    """
    config = load_recommendations_json()
    for band in config["bands"]:
        if authenticity_score <= band["max_authenticity"]:
            return band

    # Fallback to last band
    return config["bands"][-1]


def get_disclaimer() -> str:
    """Return the global disclaimer from config."""
    config = load_recommendations_json()
    return config["disclaimer"]


def build_verdict(fakeness_score: int, confidence: str) -> dict[str, Any]:
    """Build the complete verdict dict from the LLM's fakeness_score.

    Returns:
        {
            "authenticity_score": float,     # 0-10
            "fakeness_score": int,           # 0-100 (original)
            "confidence": str,
            "band_key": str,
            "band_label": str,
            "band_colour": str,
            "recommendation": str,
            "show_cross_check": bool,
            "disclaimer": str,
        }
    """
    authenticity = compute_authenticity_score(fakeness_score)
    band = select_band(authenticity)

    return {
        "authenticity_score": authenticity,
        "fakeness_score": fakeness_score,
        "confidence": confidence,
        "band_key": band["key"],
        "band_label": band["label"],
        "band_colour": band["colour"],
        "recommendation": band["recommendation"],
        "show_cross_check": band["show_cross_check"],
        "disclaimer": get_disclaimer(),
    }
